name: Bug Report
description: File a bug report
labels: [bug]
title: '[Bug]: '
body:
  - type: markdown
    attributes:
      value: 'Thanks for reporting a bug!'
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the issue.
      placeholder: 'Something is broken'
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: 'Provide exact steps, commands, or inputs.'
      placeholder: '1. Run ... 2. Observe ...'
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: 'What should have happened'
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: 'What actually happened'
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: 'Node 20, pnpm 8.x, OS'
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or Screenshots
      description: 'Attach relevant output or screenshots.'
    validations:
      required: false
